Add CI support
jfrog/jfrog-vscode-extension pull request #108
Opened 2021-07-02 05:17 UTC by RobiNino

- [ ] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

2021-07-02 05:54 UTC, yahavi commented on package.json
> +        "vscode": "^1.56.2"
What is the reason for updating the minimal version to 1.56.2?

2021-07-02 05:54 UTC, yahavi commented on package.json
> -        ]
Please put that back

2021-07-02 05:54 UTC, yahavi commented on README.md
> -
Please put that back

2021-07-13 03:13 UTC, eyalbe4 requested changes

2021-07-13 03:13 UTC, eyalbe4 commented on README.md
> +### Displaying Build Information
Displaying Build Information --> Setting Up the CI View
(let's also update the table of content).

2021-07-13 03:13 UTC, eyalbe4 commented on README.md
> +Read the [Setting up CI Integration](https://www.jfrog.com/confluence/display/JFROG/JFrog+IntelliJ+IDEA+Plugin#JFrogIntelliJIDEAPlugin-SettingupCIintegration) for more information.
Let's replace this "read more" section with a section titled as "Setting Up your CI Pipeline".
Here's the content we can add for this section:

Before VS Code can display information from your CI in the CI View, your CI pipeline needs to be configured to expose this data. Read [this guide] which describes how to configure your CI pipeline.

2021-07-13 07:05 UTC, eyalbe4 requested changes

2021-07-13 07:05 UTC, eyalbe4 commented on README.md
Let's add the following paragraph here - 

The extension also allows developers to track the status of the code while it is being built, tested and scanned on the CI server.

2021-07-13 07:08 UTC, eyalbe4 requested changes

2021-07-13 07:08 UTC, eyalbe4 commented on README.md
> +#### Setting Up Your CI Pipeline
#### --> ###
(Let's also update this section's table of content level accordingly).

2021-07-13 09:40 UTC, merged