Support Xray watches
jfrog/jfrog-vscode-extension pull request #179
Opened 2022-05-29 07:00 UTC by yahavi

- [x] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

![image](https://user-images.githubusercontent.com/11367982/170856280-36aaa6bc-03e2-429e-aa34-889f25f5ece6.png)

2022-05-29 13:37 UTC, Or-Geva requested changes

2022-05-29 13:37 UTC, Or-Geva commented on src/main/utils/configuration.ts
> +     * @returns JFrog Watches
Watches -> watches

2022-05-29 13:37 UTC, Or-Geva commented on package.json
> +                    "markdownDescription": "Optionally add one or more Xray Watches, to reflect the security policies required by your organization."
```suggestion
                    "markdownDescription": "Add one or more Xray watches, to reflect the security policies required by your organization."
```

2022-05-31 08:02 UTC, eyalbe4 requested changes

2022-05-31 11:31 UTC, merged