Add general analyzer manager tests
jfrog/jfrog-vscode-extension pull request #312
Opened 2023-03-27 13:20 UTC by attiasas

- [ ] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

2023-03-29 14:07 UTC, Or-Geva requested changes

2023-03-29 15:07 UTC, attiasas commented on src/main/scanLogic/scanRunners/binaryRunner.ts
>              if (optional) {
we first take the environment variable is they exists and store them in proxyHttpUrl/proxyHttpsUrl.
if the proxy settings in vscode is defined it takes priorty and override the value in variable.
all the changes and checks are preformed on the local variable, if both sources not exists the local variable will remain undefined and we will not change binaryVars at all

2023-03-29 15:07 UTC, attiasas commented on src/main/scanLogic/scanRunners/binaryRunner.ts
> +    public createEnvForRun(executionLogDirectory?: string): NodeJS.ProcessEnv | undefined {
I don't think so, this is per request argument, like directory it changes each scan. for each run we create temporary folder to serve as an environment for the binary to run inside, this is the value that is passed to it and the destination that the log will be created inside

2023-03-29 15:08 UTC, attiasas commented on src/main/scanLogic/scanRunners/applicabilityScan.ts
> +        return this.run(checkCancel, request).then(response => this.generateResponse(response?.runs[0]));
should wait, thanks

2023-03-30 05:53 UTC, Or-Geva commented on src/main/scanLogic/scanRunners/binaryRunner.ts
> +        let args: RunArgs = this.createRunArguments(...requests);
I understand your point. As I see it, the only purpose of passing `requests` to the Run function is to pass it along to another function. Why not follow a more conventional approach and replace requests: `AnalyzeScanRequest[] `with args: `RunArgs`?

2023-03-30 07:25 UTC, Or-Geva requested changes

2023-03-30 07:25 UTC, Or-Geva commented on src/main/scanLogic/scanRunners/binaryRunner.ts
> +    private copyRunLogToFolder(args: RunArgs, hadError: boolean) {
Let's add a tests for this copy function

2023-03-30 07:25 UTC, Or-Geva commented on src/test/tests/scanAnlayzerRunner.test.ts
> +        it('Create environment variables for binary execution - ' + test.name, () => {
`it` title should be clear about what is being tested and/or the expected results

2023-03-30 07:29 UTC, attiasas commented on src/main/scanLogic/scanRunners/binaryRunner.ts
> +        let args: RunArgs = this.createRunArguments(...requests);
changed the name of request to args

2023-03-30 07:39 UTC, attiasas commented on src/main/scanLogic/scanRunners/binaryRunner.ts
> +        let binaryVars: NodeJS.ProcessEnv = { JFROG_CLI_LOG_LEVEL: Translators.toAnalyzerLogLevel(Configuration.getLogLevel()) };
this variable sets the log level for the analyzer manager to be the same as the log level in the vscode extension
![image](https://user-images.githubusercontent.com/49212512/228764126-164b4806-4590-4341-af2b-e9877b928a74.png)

2023-03-30 08:39 UTC, attiasas commented on src/main/scanLogic/scanRunners/binaryRunner.ts
> +        args.requests.forEach(request => request.rawRequests.forEach(raw => raw.roots.forEach(root => roots.add(Utils.getLastSegment(root)))));
changed runArgs to class and moved it inside

2023-03-30 08:39 UTC, attiasas commented on src/main/scanLogic/scanRunners/binaryRunner.ts
>          let actualRequest: { requests: AnalyzeScanRequest[]; responsePaths: string[] } = { requests: [], responsePaths: [] };
removed

2023-03-30 08:53 UTC, merged