Add applicability scan tests
jfrog/jfrog-vscode-extension pull request #323
Opened 2023-04-02 11:06 UTC by attiasas

- [ ] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

2023-04-03 15:28 UTC, Or-Geva commented
It is a bit difficult to read and understand each test case, there are a lot of details to understand before the tests make any sense. in some of your tests, you did a really good job separating the test into the preparation and testing sections. This can be further divided into 1) build 2) operate 3) test/check pattern.

Moreover, I think the best thing we can do is that the number of asserts in a test should be minimized to one or two.
A single concept per test is ideal, we do not want long, difficult-to-understand tests.
This would result in independent, fast, and readable tests. It would be easy to figure out what the tests are actually testing.

You can get ideas from [here](https://github.com/jfrog/jfrog-vscode-extension/blob/master/src/test/tests/npmCmd.test.ts) regarding clean test patterns.

2023-04-10 06:43 UTC, Or-Geva requested changes

2023-04-10 06:43 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +            });
Let's break this if into two separate tests

2023-04-10 06:43 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +        describe('Generate response - ' + test.name, () => {
The `describe` should not be in a foreach loop, as it will be generated for each test case.
The `describe` is a more general thing.

2023-04-10 06:43 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
>              if (test.file) {
Let's break this `if` into separate tests using `describe`.

2023-04-10 06:43 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +                    describe('Check ' + evidence.cve + ' applicable evidences', () => {
`describe` is used to structure your test suite. There is no reason to use it as an individual test case.

2023-04-10 09:51 UTC, attiasas commented on src/test/tests/applicabilityScan.test.ts
> +    }
there is no real use to it as class, no methods or any changes in what it holds. it is a container to hold all the arguments for the scan. I don't see any use in making it a class

2023-04-10 09:56 UTC, attiasas commented on src/test/tests/applicabilityScan.test.ts
>          it('Generate Yaml request - ' + test.name, () => {
yes, for the following test cases the final test name will be:
Generate Yaml request - One root
Generate Yaml request - Multiple roots

I think it is clear what we are testing -> generating Yaml request string. Do you have any other suggestions for it to make it clearer?

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +        it('Check generated Yaml request - ' + test.name, () => {
Check generated Yaml request for one project

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +            file: path.join(scanApplicable, 'requestOneRoot.yaml'),
expectedYaml

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +            let actualPath: string = path.join(tempFolder, test.name);
actualYaml

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +describe('Contextual Analysis Scan Tests', () => {
```suggestion
describe('Applicability Scan Tests', () => {
```

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +    describe('Analyzer run fail tests', () => {
```suggestion
    describe('Applicability scan fails', () => {
```

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +        it('Check response attributes', () => {
```suggestion
        it('Check response attributes are not exist', () => {
```

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +
Remove new line

2023-04-17 09:33 UTC, Or-Geva commented on src/test/tests/applicabilityScan.test.ts
> +    describe('Populate applicable information tests', () => {
We should also add tests for unknown applicable Cve

2023-04-17 09:38 UTC, Or-Geva commented
@attiasas, the code is much cleaner and more readable now. You did an excellent job.

2023-04-18 08:58 UTC, attiasas commented on src/test/tests/applicabilityScan.test.ts
> +    describe('Populate applicable information tests', () => {
unknown? 
we have to provide the list of the CVE to scan so we have to have a specific CVE to run on.
In addition there are only two results to the scanner:
fail = applicable issue (checked under describe 'Applicable Cve tests')
pass = not applicable issue (checked under describe 'Not applicable Cve tests')

2023-04-18 08:59 UTC, attiasas commented on src/test/tests/applicabilityScan.test.ts
> +        it('Check generated Yaml request - ' + test.name, () => {
this is table test, I'm checking here both for one or multiple roots.
It cover both, the name of the test will be with prefix that describes the actual test, after '-' describes the input to test one/multiple projects

2023-04-18 10:42 UTC, merged