Add Infrastructure As Code advance scan
jfrog/jfrog-vscode-extension pull request #339
Opened 2023-04-27 09:09 UTC by attiasas

- [ ] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----

depend on https://github.com/jfrog/jfrog-vscode-extension/pull/333

2023-05-02 07:03 UTC, yahavi requested changes

2023-05-03 16:16 UTC, attiasas commented on README.md
> +| Infrastructure As Code (Iac)                               |  ✅  |   ✅   |   ✅    |  ✅  |    ✅    |   ✅    |
removed from doc until official release

2023-05-03 16:16 UTC, attiasas commented on README.md
> +| Infrastructure As Code (Iac)                               |  ✅  |   ✅   |   ✅    |  ✅  |    ✅    |   ✅    |
removed from doc until official release

2023-05-03 16:16 UTC, attiasas commented on src/main/treeDataProviders/utils/analyzerUtils.ts
>      public static parseLocationFilePath(filePath: string): string {
this is not a bug, this is how the SARIF format works, it's not supposed to depend on the platform the tool is running on.
I added explanation and changed the method to be more efficient

2023-05-03 16:16 UTC, attiasas commented on src/main/treeDataProviders/utils/analyzerUtils.ts
> +     * Populate Iac information in
nice, added the missing doc

2023-05-04 07:55 UTC, merged