Make sure the webview is loaded before sending requests
jfrog/jfrog-vscode-extension pull request #452
Opened 2023-12-04 15:36 UTC by Or-Geva

- [ ] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----
Before this pull request, there was a potential for the Webview to take longer to load than the duration between the IDE sending the first request to the Webview. To address this issue, we now ensure that we wait for a signal indicating the completion of the webview's full loading process before sending any requests.

Dependent on: 
* https://github.com/jfrog/jfrog-ide-webview/pull/51

2023-12-19 16:36 UTC, yahavi requested changes
I'm getting an infinite waiting view after clicking on any component:
![image](https://github.com/jfrog/jfrog-vscode-extension/assets/11367982/961fe858-2951-4c57-afef-3a3c86b52161)

2023-12-19 16:36 UTC, yahavi commented on src/main/webview/event/eventManager.ts
> +    private static TIMEOUT_THREE_MINUTES_IN_MS: number = 3 * 60 * 1000;
There is no point in mentioning the timeout value in the key
```suggestion
    private static TIMEOUT_MILLISECS: number = 3 * 60 * 1000;
```

2023-12-19 16:36 UTC, yahavi commented on src/main/webview/event/eventManager.ts
> +    private static RETRY_DELAY_TEN_MS: number = 3 * 60 * 1000;
```suggestion
    private static RETRY_DELAY_MILLISECS: number = 3 * 60 * 1000;
```

2023-12-19 16:36 UTC, yahavi commented on src/main/webview/event/eventManager.ts
> +            eventManager.send.setEventEmitter();
This method is async. Is it intended to not awaiting?

2023-12-20 07:18 UTC, Or-Geva commented on src/main/webview/webviewSidebar.ts
> +        webview.onDidChangeVisibility(async () => {
Im not sure im getting your point but we have already performed a cleanup at `currentWebview.onDidDispose` line 28

2023-12-20 08:04 UTC, yahavi commented on src/main/webview/webviewSidebar.ts
> +        webview.onDidChangeVisibility(async () => {
I believe that there is a reason that onDidChangeVisibility returns a disposable. Are you sure that currentWebview.onDidDispose disposes of this listener?

2023-12-24 12:17 UTC, yahavi approved these changes
LGTM

2023-12-24 13:33 UTC, merged