Allow update a dependency to fixed version from tree
jfrog/jfrog-vscode-extension pull request #83
Opened 2020-12-23 19:03 UTC by Or-Geva

- [ ] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [ ] I used `npm run format` for formatting the code before submitting the pull request.
-----
**What is it?** 
 * Allow update a dependency to fixed version from tree

**How to use it?**
 * Go to:  JFrog-Extention -> Tree -> Chose a node which includes fixed version -> Click on the arrow-up.
 
 **Supported Languages**
  * NPM
  * Maven
  * Go

2020-12-24 09:41 UTC, yahavi requested changes
Looks good! Please consider the following:
1. When an error occurred (i.e. when the dependency doesn't exist), focus on the log and/or toast an error.
2. I'd like to make the process more visible to the users. Please focus on the relevant location in the descriptor file, i.e. the <version> of the dependency in the pom.xml. Same as the eye button does, but focus on the version. 
3. Since the process runs an external process, please consider also adding a progress bar.

I'll review you code afterward. Thanks!

2020-12-27 09:08 UTC, Or-Geva commented
The following improvements were added:
  1. When an error occurred, focus on the log and/or toast an error.
  2. Focus on the relevant location in the descriptor file if the dependency updated.
  3. Add a progress bar while updating dependency

2020-12-27 17:05 UTC, yahavi requested changes

2020-12-27 17:05 UTC, yahavi commented on src/main/DependencyUpdate/goDependencyUpdate.ts
> +        }
Please put all preconditions like this in an overriding `isMatched` function. Same for npm and Maven

2020-12-27 17:10 UTC, yahavi commented on src/main/DependencyUpdate/updateDependencyManager.ts
> +        let uniqueFixedVersions: string[] = fixedVersions.toArray();
```suggestion
        let fixedVersionsArr: string[] = fixedVersions.toArray();
```

2020-12-28 07:36 UTC, Or-Geva commented on src/main/utils/mavenUtils.ts
>              node.contextValue = '';
Yea!.

2020-12-28 07:38 UTC, Or-Geva commented on src/main/commands/commandManager.ts
> +        await vscode.window.withProgress(
its title doesn't fit

2020-12-28 11:23 UTC, yahavi approved these changes

2020-12-28 11:24 UTC, merged