Allow disabling scan upon changes - readme
jfrog/jfrog-vscode-extension pull request #91
Opened 2021-01-03 12:31 UTC by yahavi

- [x] All [tests](https://github.com/jfrog/jfrog-vscode-extension#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] I used `npm run format` for formatting the code before submitting the pull request.
-----

Readme updates for #90

2021-01-03 13:12 UTC, talarian1 approved these changes

2021-01-03 17:01 UTC, eyalbe4 requested changes

2021-01-03 17:01 UTC, eyalbe4 commented on README.md
> +The JFrog VS-Code extension can trigger an Xray scan after a change in go.sum and package-lock.json.
... in go.sum and package-lock.json. -->  in go.sum or package-lock.json.

2021-02-20 21:24 UTC, eyalbe4 approved these changes

2021-02-21 07:08 UTC, merged